name: build
env:
    TZ: Asia/Shanghai

on:
  schedule:
      # 每6小时跑一遍，第5小时会用kill打断并保存编译缓存ccache，
    - cron:  '0 2,8,14,20 * * *' # 时区对cron无效，所以要提前8个小时，
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - uses: actions/checkout@v2
    - name: env
      run: |
        echo "START_TIME=$(date '+%s')" >> $GITHUB_ENV
        mkdir -p "$PWD/run"
        echo "FLAG_STOP=$PWD/run/ninjaStop" >> $GITHUB_ENV
        echo "ROOT=$PWD" >> $GITHUB_ENV

    - run: lscpu
    - run: df -h
    - run: cd $ROOT/cache && du -h && ( ls -lR | grep "^-" | wc -l ) || true
    - run: chmod -R a+x $ROOT/script/
    - run: $ROOT/script/create_ccache_config.sh
    - run: $ROOT/script/download_depot.sh        
    - run: $ROOT/script/download_src.sh    
    - run: $ROOT/script/gen.sh
    - run: $ROOT/script/auto_kill.sh
    - run: df -h
    
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    
    - run: ccache -s
    - run: $ROOT/script/build_step.sh base_unittests.exe
    - run: df -h
    - run: ccache -s
    - run: killall sleep && ( ls -a $ROOT/chromium/src/out/ || true )

    - name: 提交更改
      run: |
        cd $ROOT
        git config core.ignorecase false
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add ./cache
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')更新" || echo no change,
        git push origin main
