name: build
env:
    TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: env
      run: |
        echo "START_TIME=$(date '+%s')" >> $GITHUB_ENV
        mkdir -p "$PWD/run"
        echo "FLAG_STOP=$PWD/run/ninjaStop" >> $GITHUB_ENV
        echo "ROOT=$PWD" >> $GITHUB_ENV

    - run: lscpu
    - run: free -m
    - run: df -h
    - run: chmod -R a+x $ROOT/script/
    - run: $ROOT/script/create_ccache_config.sh
    - run: $ROOT/script/maximize_build_space.sh
    - run: df -h
    - run: $ROOT/script/download_depot.sh
    - run: $ROOT/script/download_src.sh
    - run: $ROOT/script/gen.sh
    - run: $ROOT/script/auto_kill.sh
    - run: $ROOT/script/build_step.sh

    - name: 提交更改
      run: |
        git config core.ignorecase false
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add "$HOME/cache"
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')更新" || echo no change,
        git pull origin main
        git push origin main
